### ISSUE TITLE
[Feature] Create Form Component

### ISSUE THREAD

**Issue by DanielLoredo** [DanielLoredo/RoboLinks-FrontEnd#8]
**Task**

- Create the Form Component as a Modal/PopUp
- For this issue only the styling for "Name", "URL" and "ShortURL" inputs are required

**Note**

- Only styling is required, we are going to handle functionality after the Backend is deployed
- You can use React Portals or another approach for the Modal

**Comment by AuroTB** [comment]
Previews:
![image](https://user-images.githubusercontent.com/25405578/114125368-f1533300-98bb-11eb-8343-df44bc9a16c8.png)
![image](https://user-images.githubusercontent.com/25405578/114125463-23649500-98bc-11eb-8684-5223d0e6309a.png)
